// Code generated by ent, DO NOT EDIT.

package datasource

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the datasource type in the database.
	Label = "data_source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldLastIndexed holds the string denoting the last_indexed field in the database.
	FieldLastIndexed = "last_indexed"
	// FieldDateAdded holds the string denoting the date_added field in the database.
	FieldDateAdded = "date_added"
	// Table holds the table name of the datasource in the database.
	Table = "data_sources"
)

// Columns holds all SQL columns for datasource fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldType,
	FieldStatus,
	FieldConfig,
	FieldLastIndexed,
	FieldDateAdded,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultLastIndexed holds the default value on creation for the "last_indexed" field.
	DefaultLastIndexed func() time.Time
	// DefaultDateAdded holds the default value on creation for the "date_added" field.
	DefaultDateAdded func() time.Time
)

// OrderOption defines the ordering options for the DataSource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByConfig orders the results by the config field.
func ByConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfig, opts...).ToFunc()
}

// ByLastIndexed orders the results by the last_indexed field.
func ByLastIndexed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastIndexed, opts...).ToFunc()
}

// ByDateAdded orders the results by the date_added field.
func ByDateAdded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateAdded, opts...).ToFunc()
}
