// Code generated by ent, DO NOT EDIT.

package datasource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/compy/finder.sh/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DataSource {
	return predicate.DataSource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DataSource {
	return predicate.DataSource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DataSource {
	return predicate.DataSource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DataSource {
	return predicate.DataSource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DataSource {
	return predicate.DataSource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DataSource {
	return predicate.DataSource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DataSource {
	return predicate.DataSource(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldStatus, v))
}

// Config applies equality check predicate on the "config" field. It's identical to ConfigEQ.
func Config(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldConfig, v))
}

// LastIndexed applies equality check predicate on the "last_indexed" field. It's identical to LastIndexedEQ.
func LastIndexed(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldLastIndexed, v))
}

// DateAdded applies equality check predicate on the "date_added" field. It's identical to DateAddedEQ.
func DateAdded(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldDateAdded, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DataSource {
	return predicate.DataSource(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DataSource {
	return predicate.DataSource(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.DataSource {
	return predicate.DataSource(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.DataSource {
	return predicate.DataSource(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldContainsFold(FieldType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DataSource {
	return predicate.DataSource(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DataSource {
	return predicate.DataSource(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldContainsFold(FieldStatus, v))
}

// ConfigEQ applies the EQ predicate on the "config" field.
func ConfigEQ(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldConfig, v))
}

// ConfigNEQ applies the NEQ predicate on the "config" field.
func ConfigNEQ(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldNEQ(FieldConfig, v))
}

// ConfigIn applies the In predicate on the "config" field.
func ConfigIn(vs ...string) predicate.DataSource {
	return predicate.DataSource(sql.FieldIn(FieldConfig, vs...))
}

// ConfigNotIn applies the NotIn predicate on the "config" field.
func ConfigNotIn(vs ...string) predicate.DataSource {
	return predicate.DataSource(sql.FieldNotIn(FieldConfig, vs...))
}

// ConfigGT applies the GT predicate on the "config" field.
func ConfigGT(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldGT(FieldConfig, v))
}

// ConfigGTE applies the GTE predicate on the "config" field.
func ConfigGTE(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldGTE(FieldConfig, v))
}

// ConfigLT applies the LT predicate on the "config" field.
func ConfigLT(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldLT(FieldConfig, v))
}

// ConfigLTE applies the LTE predicate on the "config" field.
func ConfigLTE(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldLTE(FieldConfig, v))
}

// ConfigContains applies the Contains predicate on the "config" field.
func ConfigContains(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldContains(FieldConfig, v))
}

// ConfigHasPrefix applies the HasPrefix predicate on the "config" field.
func ConfigHasPrefix(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldHasPrefix(FieldConfig, v))
}

// ConfigHasSuffix applies the HasSuffix predicate on the "config" field.
func ConfigHasSuffix(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldHasSuffix(FieldConfig, v))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.DataSource {
	return predicate.DataSource(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.DataSource {
	return predicate.DataSource(sql.FieldNotNull(FieldConfig))
}

// ConfigEqualFold applies the EqualFold predicate on the "config" field.
func ConfigEqualFold(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldEqualFold(FieldConfig, v))
}

// ConfigContainsFold applies the ContainsFold predicate on the "config" field.
func ConfigContainsFold(v string) predicate.DataSource {
	return predicate.DataSource(sql.FieldContainsFold(FieldConfig, v))
}

// LastIndexedEQ applies the EQ predicate on the "last_indexed" field.
func LastIndexedEQ(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldLastIndexed, v))
}

// LastIndexedNEQ applies the NEQ predicate on the "last_indexed" field.
func LastIndexedNEQ(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldNEQ(FieldLastIndexed, v))
}

// LastIndexedIn applies the In predicate on the "last_indexed" field.
func LastIndexedIn(vs ...time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldIn(FieldLastIndexed, vs...))
}

// LastIndexedNotIn applies the NotIn predicate on the "last_indexed" field.
func LastIndexedNotIn(vs ...time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldNotIn(FieldLastIndexed, vs...))
}

// LastIndexedGT applies the GT predicate on the "last_indexed" field.
func LastIndexedGT(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldGT(FieldLastIndexed, v))
}

// LastIndexedGTE applies the GTE predicate on the "last_indexed" field.
func LastIndexedGTE(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldGTE(FieldLastIndexed, v))
}

// LastIndexedLT applies the LT predicate on the "last_indexed" field.
func LastIndexedLT(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldLT(FieldLastIndexed, v))
}

// LastIndexedLTE applies the LTE predicate on the "last_indexed" field.
func LastIndexedLTE(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldLTE(FieldLastIndexed, v))
}

// DateAddedEQ applies the EQ predicate on the "date_added" field.
func DateAddedEQ(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldEQ(FieldDateAdded, v))
}

// DateAddedNEQ applies the NEQ predicate on the "date_added" field.
func DateAddedNEQ(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldNEQ(FieldDateAdded, v))
}

// DateAddedIn applies the In predicate on the "date_added" field.
func DateAddedIn(vs ...time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldIn(FieldDateAdded, vs...))
}

// DateAddedNotIn applies the NotIn predicate on the "date_added" field.
func DateAddedNotIn(vs ...time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldNotIn(FieldDateAdded, vs...))
}

// DateAddedGT applies the GT predicate on the "date_added" field.
func DateAddedGT(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldGT(FieldDateAdded, v))
}

// DateAddedGTE applies the GTE predicate on the "date_added" field.
func DateAddedGTE(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldGTE(FieldDateAdded, v))
}

// DateAddedLT applies the LT predicate on the "date_added" field.
func DateAddedLT(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldLT(FieldDateAdded, v))
}

// DateAddedLTE applies the LTE predicate on the "date_added" field.
func DateAddedLTE(v time.Time) predicate.DataSource {
	return predicate.DataSource(sql.FieldLTE(FieldDateAdded, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DataSource) predicate.DataSource {
	return predicate.DataSource(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DataSource) predicate.DataSource {
	return predicate.DataSource(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DataSource) predicate.DataSource {
	return predicate.DataSource(func(s *sql.Selector) {
		p(s.Not())
	})
}
