// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/compy/finder.sh/ent/datasource"
	"github.com/compy/finder.sh/ent/group"
	"github.com/compy/finder.sh/ent/passwordtoken"
	"github.com/compy/finder.sh/ent/schema"
	"github.com/compy/finder.sh/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	datasourceFields := schema.DataSource{}.Fields()
	_ = datasourceFields
	// datasourceDescType is the schema descriptor for type field.
	datasourceDescType := datasourceFields[1].Descriptor()
	// datasource.DefaultType holds the default value on creation for the type field.
	datasource.DefaultType = datasourceDescType.Default.(string)
	// datasourceDescStatus is the schema descriptor for status field.
	datasourceDescStatus := datasourceFields[2].Descriptor()
	// datasource.DefaultStatus holds the default value on creation for the status field.
	datasource.DefaultStatus = datasourceDescStatus.Default.(string)
	// datasourceDescLastIndexed is the schema descriptor for last_indexed field.
	datasourceDescLastIndexed := datasourceFields[4].Descriptor()
	// datasource.DefaultLastIndexed holds the default value on creation for the last_indexed field.
	datasource.DefaultLastIndexed = datasourceDescLastIndexed.Default.(func() time.Time)
	// datasourceDescDateAdded is the schema descriptor for date_added field.
	datasourceDescDateAdded := datasourceFields[5].Descriptor()
	// datasource.DefaultDateAdded holds the default value on creation for the date_added field.
	datasource.DefaultDateAdded = datasourceDescDateAdded.Default.(func() time.Time)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupFields[1].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	passwordtokenFields := schema.PasswordToken{}.Fields()
	_ = passwordtokenFields
	// passwordtokenDescHash is the schema descriptor for hash field.
	passwordtokenDescHash := passwordtokenFields[0].Descriptor()
	// passwordtoken.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	passwordtoken.HashValidator = passwordtokenDescHash.Validators[0].(func(string) error)
	// passwordtokenDescCreatedAt is the schema descriptor for created_at field.
	passwordtokenDescCreatedAt := passwordtokenFields[1].Descriptor()
	// passwordtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordtoken.DefaultCreatedAt = passwordtokenDescCreatedAt.Default.(func() time.Time)
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescVerified is the schema descriptor for verified field.
	userDescVerified := userFields[3].Descriptor()
	// user.DefaultVerified holds the default value on creation for the verified field.
	user.DefaultVerified = userDescVerified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}

const (
	Version = "v0.12.3"                                         // Version of ent codegen.
	Sum     = "h1:N5lO2EOrHpCH5HYfiMOCHYbo+oh5M8GjT0/cx5x6xkk=" // Sum of ent codegen.
)
