// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/compy/finder.sh/ent/datasource"
	"github.com/compy/finder.sh/ent/predicate"
)

// DataSourceUpdate is the builder for updating DataSource entities.
type DataSourceUpdate struct {
	config
	hooks    []Hook
	mutation *DataSourceMutation
}

// Where appends a list predicates to the DataSourceUpdate builder.
func (dsu *DataSourceUpdate) Where(ps ...predicate.DataSource) *DataSourceUpdate {
	dsu.mutation.Where(ps...)
	return dsu
}

// SetName sets the "name" field.
func (dsu *DataSourceUpdate) SetName(s string) *DataSourceUpdate {
	dsu.mutation.SetName(s)
	return dsu
}

// SetType sets the "type" field.
func (dsu *DataSourceUpdate) SetType(s string) *DataSourceUpdate {
	dsu.mutation.SetType(s)
	return dsu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (dsu *DataSourceUpdate) SetNillableType(s *string) *DataSourceUpdate {
	if s != nil {
		dsu.SetType(*s)
	}
	return dsu
}

// SetStatus sets the "status" field.
func (dsu *DataSourceUpdate) SetStatus(s string) *DataSourceUpdate {
	dsu.mutation.SetStatus(s)
	return dsu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (dsu *DataSourceUpdate) SetNillableStatus(s *string) *DataSourceUpdate {
	if s != nil {
		dsu.SetStatus(*s)
	}
	return dsu
}

// SetConfig sets the "config" field.
func (dsu *DataSourceUpdate) SetConfig(s string) *DataSourceUpdate {
	dsu.mutation.SetConfig(s)
	return dsu
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (dsu *DataSourceUpdate) SetNillableConfig(s *string) *DataSourceUpdate {
	if s != nil {
		dsu.SetConfig(*s)
	}
	return dsu
}

// ClearConfig clears the value of the "config" field.
func (dsu *DataSourceUpdate) ClearConfig() *DataSourceUpdate {
	dsu.mutation.ClearConfig()
	return dsu
}

// SetLastIndexed sets the "last_indexed" field.
func (dsu *DataSourceUpdate) SetLastIndexed(t time.Time) *DataSourceUpdate {
	dsu.mutation.SetLastIndexed(t)
	return dsu
}

// SetNillableLastIndexed sets the "last_indexed" field if the given value is not nil.
func (dsu *DataSourceUpdate) SetNillableLastIndexed(t *time.Time) *DataSourceUpdate {
	if t != nil {
		dsu.SetLastIndexed(*t)
	}
	return dsu
}

// SetDateAdded sets the "date_added" field.
func (dsu *DataSourceUpdate) SetDateAdded(t time.Time) *DataSourceUpdate {
	dsu.mutation.SetDateAdded(t)
	return dsu
}

// SetNillableDateAdded sets the "date_added" field if the given value is not nil.
func (dsu *DataSourceUpdate) SetNillableDateAdded(t *time.Time) *DataSourceUpdate {
	if t != nil {
		dsu.SetDateAdded(*t)
	}
	return dsu
}

// Mutation returns the DataSourceMutation object of the builder.
func (dsu *DataSourceUpdate) Mutation() *DataSourceMutation {
	return dsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dsu *DataSourceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, dsu.sqlSave, dsu.mutation, dsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dsu *DataSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := dsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dsu *DataSourceUpdate) Exec(ctx context.Context) error {
	_, err := dsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dsu *DataSourceUpdate) ExecX(ctx context.Context) {
	if err := dsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dsu *DataSourceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(datasource.Table, datasource.Columns, sqlgraph.NewFieldSpec(datasource.FieldID, field.TypeInt))
	if ps := dsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dsu.mutation.Name(); ok {
		_spec.SetField(datasource.FieldName, field.TypeString, value)
	}
	if value, ok := dsu.mutation.GetType(); ok {
		_spec.SetField(datasource.FieldType, field.TypeString, value)
	}
	if value, ok := dsu.mutation.Status(); ok {
		_spec.SetField(datasource.FieldStatus, field.TypeString, value)
	}
	if value, ok := dsu.mutation.Config(); ok {
		_spec.SetField(datasource.FieldConfig, field.TypeString, value)
	}
	if dsu.mutation.ConfigCleared() {
		_spec.ClearField(datasource.FieldConfig, field.TypeString)
	}
	if value, ok := dsu.mutation.LastIndexed(); ok {
		_spec.SetField(datasource.FieldLastIndexed, field.TypeTime, value)
	}
	if value, ok := dsu.mutation.DateAdded(); ok {
		_spec.SetField(datasource.FieldDateAdded, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{datasource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dsu.mutation.done = true
	return n, nil
}

// DataSourceUpdateOne is the builder for updating a single DataSource entity.
type DataSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DataSourceMutation
}

// SetName sets the "name" field.
func (dsuo *DataSourceUpdateOne) SetName(s string) *DataSourceUpdateOne {
	dsuo.mutation.SetName(s)
	return dsuo
}

// SetType sets the "type" field.
func (dsuo *DataSourceUpdateOne) SetType(s string) *DataSourceUpdateOne {
	dsuo.mutation.SetType(s)
	return dsuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (dsuo *DataSourceUpdateOne) SetNillableType(s *string) *DataSourceUpdateOne {
	if s != nil {
		dsuo.SetType(*s)
	}
	return dsuo
}

// SetStatus sets the "status" field.
func (dsuo *DataSourceUpdateOne) SetStatus(s string) *DataSourceUpdateOne {
	dsuo.mutation.SetStatus(s)
	return dsuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (dsuo *DataSourceUpdateOne) SetNillableStatus(s *string) *DataSourceUpdateOne {
	if s != nil {
		dsuo.SetStatus(*s)
	}
	return dsuo
}

// SetConfig sets the "config" field.
func (dsuo *DataSourceUpdateOne) SetConfig(s string) *DataSourceUpdateOne {
	dsuo.mutation.SetConfig(s)
	return dsuo
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (dsuo *DataSourceUpdateOne) SetNillableConfig(s *string) *DataSourceUpdateOne {
	if s != nil {
		dsuo.SetConfig(*s)
	}
	return dsuo
}

// ClearConfig clears the value of the "config" field.
func (dsuo *DataSourceUpdateOne) ClearConfig() *DataSourceUpdateOne {
	dsuo.mutation.ClearConfig()
	return dsuo
}

// SetLastIndexed sets the "last_indexed" field.
func (dsuo *DataSourceUpdateOne) SetLastIndexed(t time.Time) *DataSourceUpdateOne {
	dsuo.mutation.SetLastIndexed(t)
	return dsuo
}

// SetNillableLastIndexed sets the "last_indexed" field if the given value is not nil.
func (dsuo *DataSourceUpdateOne) SetNillableLastIndexed(t *time.Time) *DataSourceUpdateOne {
	if t != nil {
		dsuo.SetLastIndexed(*t)
	}
	return dsuo
}

// SetDateAdded sets the "date_added" field.
func (dsuo *DataSourceUpdateOne) SetDateAdded(t time.Time) *DataSourceUpdateOne {
	dsuo.mutation.SetDateAdded(t)
	return dsuo
}

// SetNillableDateAdded sets the "date_added" field if the given value is not nil.
func (dsuo *DataSourceUpdateOne) SetNillableDateAdded(t *time.Time) *DataSourceUpdateOne {
	if t != nil {
		dsuo.SetDateAdded(*t)
	}
	return dsuo
}

// Mutation returns the DataSourceMutation object of the builder.
func (dsuo *DataSourceUpdateOne) Mutation() *DataSourceMutation {
	return dsuo.mutation
}

// Where appends a list predicates to the DataSourceUpdate builder.
func (dsuo *DataSourceUpdateOne) Where(ps ...predicate.DataSource) *DataSourceUpdateOne {
	dsuo.mutation.Where(ps...)
	return dsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dsuo *DataSourceUpdateOne) Select(field string, fields ...string) *DataSourceUpdateOne {
	dsuo.fields = append([]string{field}, fields...)
	return dsuo
}

// Save executes the query and returns the updated DataSource entity.
func (dsuo *DataSourceUpdateOne) Save(ctx context.Context) (*DataSource, error) {
	return withHooks(ctx, dsuo.sqlSave, dsuo.mutation, dsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dsuo *DataSourceUpdateOne) SaveX(ctx context.Context) *DataSource {
	node, err := dsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dsuo *DataSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := dsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dsuo *DataSourceUpdateOne) ExecX(ctx context.Context) {
	if err := dsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dsuo *DataSourceUpdateOne) sqlSave(ctx context.Context) (_node *DataSource, err error) {
	_spec := sqlgraph.NewUpdateSpec(datasource.Table, datasource.Columns, sqlgraph.NewFieldSpec(datasource.FieldID, field.TypeInt))
	id, ok := dsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DataSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, datasource.FieldID)
		for _, f := range fields {
			if !datasource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != datasource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dsuo.mutation.Name(); ok {
		_spec.SetField(datasource.FieldName, field.TypeString, value)
	}
	if value, ok := dsuo.mutation.GetType(); ok {
		_spec.SetField(datasource.FieldType, field.TypeString, value)
	}
	if value, ok := dsuo.mutation.Status(); ok {
		_spec.SetField(datasource.FieldStatus, field.TypeString, value)
	}
	if value, ok := dsuo.mutation.Config(); ok {
		_spec.SetField(datasource.FieldConfig, field.TypeString, value)
	}
	if dsuo.mutation.ConfigCleared() {
		_spec.ClearField(datasource.FieldConfig, field.TypeString)
	}
	if value, ok := dsuo.mutation.LastIndexed(); ok {
		_spec.SetField(datasource.FieldLastIndexed, field.TypeTime, value)
	}
	if value, ok := dsuo.mutation.DateAdded(); ok {
		_spec.SetField(datasource.FieldDateAdded, field.TypeTime, value)
	}
	_node = &DataSource{config: dsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{datasource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dsuo.mutation.done = true
	return _node, nil
}
