// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/compy/finder.sh/ent/datasource"
)

// DataSourceCreate is the builder for creating a DataSource entity.
type DataSourceCreate struct {
	config
	mutation *DataSourceMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (dsc *DataSourceCreate) SetName(s string) *DataSourceCreate {
	dsc.mutation.SetName(s)
	return dsc
}

// SetType sets the "type" field.
func (dsc *DataSourceCreate) SetType(s string) *DataSourceCreate {
	dsc.mutation.SetType(s)
	return dsc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (dsc *DataSourceCreate) SetNillableType(s *string) *DataSourceCreate {
	if s != nil {
		dsc.SetType(*s)
	}
	return dsc
}

// SetStatus sets the "status" field.
func (dsc *DataSourceCreate) SetStatus(s string) *DataSourceCreate {
	dsc.mutation.SetStatus(s)
	return dsc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (dsc *DataSourceCreate) SetNillableStatus(s *string) *DataSourceCreate {
	if s != nil {
		dsc.SetStatus(*s)
	}
	return dsc
}

// SetConfig sets the "config" field.
func (dsc *DataSourceCreate) SetConfig(s string) *DataSourceCreate {
	dsc.mutation.SetConfig(s)
	return dsc
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (dsc *DataSourceCreate) SetNillableConfig(s *string) *DataSourceCreate {
	if s != nil {
		dsc.SetConfig(*s)
	}
	return dsc
}

// SetLastIndexed sets the "last_indexed" field.
func (dsc *DataSourceCreate) SetLastIndexed(t time.Time) *DataSourceCreate {
	dsc.mutation.SetLastIndexed(t)
	return dsc
}

// SetNillableLastIndexed sets the "last_indexed" field if the given value is not nil.
func (dsc *DataSourceCreate) SetNillableLastIndexed(t *time.Time) *DataSourceCreate {
	if t != nil {
		dsc.SetLastIndexed(*t)
	}
	return dsc
}

// SetDateAdded sets the "date_added" field.
func (dsc *DataSourceCreate) SetDateAdded(t time.Time) *DataSourceCreate {
	dsc.mutation.SetDateAdded(t)
	return dsc
}

// SetNillableDateAdded sets the "date_added" field if the given value is not nil.
func (dsc *DataSourceCreate) SetNillableDateAdded(t *time.Time) *DataSourceCreate {
	if t != nil {
		dsc.SetDateAdded(*t)
	}
	return dsc
}

// Mutation returns the DataSourceMutation object of the builder.
func (dsc *DataSourceCreate) Mutation() *DataSourceMutation {
	return dsc.mutation
}

// Save creates the DataSource in the database.
func (dsc *DataSourceCreate) Save(ctx context.Context) (*DataSource, error) {
	dsc.defaults()
	return withHooks(ctx, dsc.sqlSave, dsc.mutation, dsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dsc *DataSourceCreate) SaveX(ctx context.Context) *DataSource {
	v, err := dsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dsc *DataSourceCreate) Exec(ctx context.Context) error {
	_, err := dsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dsc *DataSourceCreate) ExecX(ctx context.Context) {
	if err := dsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dsc *DataSourceCreate) defaults() {
	if _, ok := dsc.mutation.GetType(); !ok {
		v := datasource.DefaultType
		dsc.mutation.SetType(v)
	}
	if _, ok := dsc.mutation.Status(); !ok {
		v := datasource.DefaultStatus
		dsc.mutation.SetStatus(v)
	}
	if _, ok := dsc.mutation.LastIndexed(); !ok {
		v := datasource.DefaultLastIndexed()
		dsc.mutation.SetLastIndexed(v)
	}
	if _, ok := dsc.mutation.DateAdded(); !ok {
		v := datasource.DefaultDateAdded()
		dsc.mutation.SetDateAdded(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dsc *DataSourceCreate) check() error {
	if _, ok := dsc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DataSource.name"`)}
	}
	if _, ok := dsc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "DataSource.type"`)}
	}
	if _, ok := dsc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DataSource.status"`)}
	}
	if _, ok := dsc.mutation.LastIndexed(); !ok {
		return &ValidationError{Name: "last_indexed", err: errors.New(`ent: missing required field "DataSource.last_indexed"`)}
	}
	if _, ok := dsc.mutation.DateAdded(); !ok {
		return &ValidationError{Name: "date_added", err: errors.New(`ent: missing required field "DataSource.date_added"`)}
	}
	return nil
}

func (dsc *DataSourceCreate) sqlSave(ctx context.Context) (*DataSource, error) {
	if err := dsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dsc.mutation.id = &_node.ID
	dsc.mutation.done = true
	return _node, nil
}

func (dsc *DataSourceCreate) createSpec() (*DataSource, *sqlgraph.CreateSpec) {
	var (
		_node = &DataSource{config: dsc.config}
		_spec = sqlgraph.NewCreateSpec(datasource.Table, sqlgraph.NewFieldSpec(datasource.FieldID, field.TypeInt))
	)
	if value, ok := dsc.mutation.Name(); ok {
		_spec.SetField(datasource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := dsc.mutation.GetType(); ok {
		_spec.SetField(datasource.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := dsc.mutation.Status(); ok {
		_spec.SetField(datasource.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := dsc.mutation.Config(); ok {
		_spec.SetField(datasource.FieldConfig, field.TypeString, value)
		_node.Config = value
	}
	if value, ok := dsc.mutation.LastIndexed(); ok {
		_spec.SetField(datasource.FieldLastIndexed, field.TypeTime, value)
		_node.LastIndexed = value
	}
	if value, ok := dsc.mutation.DateAdded(); ok {
		_spec.SetField(datasource.FieldDateAdded, field.TypeTime, value)
		_node.DateAdded = value
	}
	return _node, _spec
}

// DataSourceCreateBulk is the builder for creating many DataSource entities in bulk.
type DataSourceCreateBulk struct {
	config
	builders []*DataSourceCreate
}

// Save creates the DataSource entities in the database.
func (dscb *DataSourceCreateBulk) Save(ctx context.Context) ([]*DataSource, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dscb.builders))
	nodes := make([]*DataSource, len(dscb.builders))
	mutators := make([]Mutator, len(dscb.builders))
	for i := range dscb.builders {
		func(i int, root context.Context) {
			builder := dscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DataSourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dscb *DataSourceCreateBulk) SaveX(ctx context.Context) []*DataSource {
	v, err := dscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dscb *DataSourceCreateBulk) Exec(ctx context.Context) error {
	_, err := dscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dscb *DataSourceCreateBulk) ExecX(ctx context.Context) {
	if err := dscb.Exec(ctx); err != nil {
		panic(err)
	}
}
