// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DataSource is the predicate function for datasource builders.
type DataSource func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// PasswordToken is the predicate function for passwordtoken builders.
type PasswordToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
